### ISSUE TITLE
Describe how to use remote fs as primary fs only

### ISSUE THREAD

**Issue by przem123** [IBM/ibm-spectrum-scale-csi-operator#110]
In the configuration yaml you describe how to use a remote filesystem. I would need to use one as my primary fs, I dont want use any local filesystems. How should the configuration look like ? Should the primary cluster ID be my remote ID ? Do I need to specify credentials for my local GUI as I only intend to use my remote filesystems ? Or only for the remote GUI?

```
  clusters:
    - id: "< Primary Cluster ID - WARNING: THIS IS A STRING NEEDS YAML QUOTES!>"
      secrets: "secret1"
      secureSslMode: false
      primary:
        primaryFs: "< Primary Filesystem >"
        primaryFset: "< Fileset in Primary Filesystem >"
#        inodeLimit: "< node limit for Primary Fileset >" # Optional
#        remoteCluster: "< Remote ClusterID >"            # Optional - This ID should have seperate entry in Clusters map.
#        remoteFs: "< Remote Filesystem >"                # Optional
#      cacert: "< CA cert configmap for GUI >"            # Optional
      restApi: 
      - guiHost: "< Primary cluster GUI IP/Hostname >" 
```
Can you provide a basic sample for a single remote fs only?
