### ISSUE TITLE
Operator Resource Delete Doesn't Delete  Resources

### ISSUE THREAD

**Issue by mew2057** [IBM/ibm-spectrum-scale-csi-operator#23]
When deleting the Operator Resource through `kubectl delete` the cascading delete doesn't trigger:

``` bash
[root ibm-spectrum-scale-csi-operator]# kubectl get pods
NAME                                               READY   STATUS    RESTARTS   AGE
csi-spectrum-scale-attacher-0                      1/1     Running   0          6m47s
csi-spectrum-scale-lh9j2                           2/2     Running   0          6m57s
csi-spectrum-scale-provisioner-0                   1/1     Running   0          6m26s
csi-spectrum-scale-r6mc7                           2/2     Running   0          6m57s
```

**Comment by mew2057** [comment]
This only recently surfaced (this week), not 100% sure on the source of the issue, as previous iterations worked fine.

**Comment by mew2057** [comment]
Reverting to `quay.io/operator-framework/ansible-operator:v0.8.0`

**Comment by mew2057** [comment]
> Reverting to `quay.io/operator-framework/ansible-operator:v0.8.0`

This didn't work, investigating operator-framework source to see if I can debug a CR delete.

**Comment by mew2057** [comment]
Sourced the issue, the finalizer stopped being triggered. Updated `watches.yaml`:

``` YAML
--
- version: v1alpha1
  group: scale.ibm.com
  kind: CSIScaleOperator
  role: /opt/ansible/roles/csi-scale
  ManageStatus: True
  finalizer:
    name: finalizer.scale.ibm.com
    vars:
      state: absent
```
