### ISSUE TITLE
Molecule Initial Setup

### ISSUE THREAD

**Issue by mew2057** [IBM/ibm-spectrum-scale-csi-operator#36]
Molecule needs to be initialized and green for before we can start writing additional tests. Right now there's a failure relating to missing variables:

```
TASK [csi-scale : Ensure scale_config] *****************************************

    fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'spec'\n\nThe error appears to be in '/home/travis/build/mew2057/ibm-spectrum-scale-csi-operator/stable/ibm-spectrum-scale-csi-operator-bundle/operators/ibm-spectrum-scale-csi-operator/roles/csi-scale/tasks/plugin_config.yml': line 2, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n---\n- name: \"Ensure scale_config\"\n  ^ here\n"}
```

This is likely indicative that we're handling variables wrong in the role. 

This issue is a tracking issue for getting molecule to the `green` state.

**Comment by mew2057** [comment]
- [ ] Remove `_scale_ibm_com_csiscaleoperator` from the task file. It places too much dependence on the operator framework and reduces the overall flexibility of the operator.

- [ ] Add sensible defaults for variables that may be missing.

**Comment by mew2057** [comment]
It looks like `camelCase` variables aren't put into the `vars` for the ansible playbook:

``` YAML

apiVersion: scale.ibm.com/v1alpha1
kind: 'CSIScaleOperator'
metadata:
    # IMPORTANT THE OPERATOR LOOKS FOR THIS!
    name: 'csi-scale-operator'
status: {}
spec:
  #
  scaleHostpath: "/ibm/fs1"
  secretCounter: 1000
  attacher: "test123"
  provisioner: "test23"
  driverRegistrar: "test3"
  spectrumScale: "test"

  clusters:
    - id: "11832033572270148010"
      secrets: "secret1"
      secureSslMode: false
      primary:
        primaryFS: "fs1"
        primaryFset: "csiFset2"
      restApi:
      - guiHost: "jdunham-rh72-k8s-scale-master.fyre.ibm.com"
```

`attacher`, `provisioner` and `cluster` are all processed, but  `scaleHostpath`, `secretCounter, `driverRegistrar` and `spectrumScale` are all set to their defaults.
``` bash
TASK [csi-scale : debug] *******************************************************
task path: /opt/ansible/roles/csi-scale/tasks/main.yml:9
ok: [localhost] => {
    "msg": [
        "scaleHostpath - /",
        "secretCounter - -1",
        "attacher - test123",
        "provisioner - test23",
        "driverRegistrar -quay.io/k8scsi/csi-node-driver-registrar:v1.0.1",
        "spectrumScale - quay.io/mew2057/ibm-spectrum-scale-csi-driver:v0.9.0"
    ]
}
META: ending play
```

**Comment by mew2057** [comment]
Looked into it and lo and behold the operator changes the case:
```
5150             "driverRegistrar": "quay.io/k8scsi/csi-node-driver-registrar:v1.0.1",^M
5151             "driver_registrar": "test3",^M
```

**Comment by mew2057** [comment]
``` YAML
## defaults//main.yml
---
# defaults file for ansible-role-csi-scale
name: "csi-spectrum-scale"
namespace: '{{ meta.namespace }}'
storage-class: "csi-spectrum-scale"


# Image defaults
attacher:    "quay.io/k8scsi/csi-attacher:v1.0.0"
provisioner: "quay.io/k8scsi/csi-provisioner:v1.0.0"

# Due to camelCase these get loaded differently in the operator.
driverRegistrar: "{{ driver_registrar | default('quay.io/k8scsi/csi-node-driver-registrar:v1.0.1') }}"
spectrumScale:   "{{ spectrum_scale   | default('quay.io/mew2057/ibm-spectrum-scale-csi-driver:v0.9.0') }}"

# Set defaults for the secret counter and hostpath.
secretCounter: "{{ secret_counter |  default(-1) }}"
scaleHostpath: "{{ scale_hostpath | default('/') }}"




# State of driver in the cluster (might not be needed).
#state: absent
state: present
```
