### ISSUE TITLE
Resource parameters needed in operator.yaml

### ISSUE THREAD

**Issue by mew2057** [IBM/ibm-spectrum-scale-csi-operator#46]
The `operator.yaml` configuration requires a `resources` section for each container.

**Describe the solution you'd like**
Each container needs a section roughly like this:
``` YAML
resources:
  requests:
    memory: "32Mi"
    cpu: "100m"
  limits:
    memory: "128Mi"
    cpu: "500m" 
```

In order to achieve this it is necessary to determine the operating parameters of the various containers. To this end a test case should be developed to stress each container to guage the extents of operation.

**THIS IS NEEDED FOR CERT!**
